# Conda environment for developing tsdat pipelines

name: tsdat-pipelines
channels:
  - arm-doe
  - conda-forge
dependencies:
  - python=3.10
  - adi_py>=3.19.2
  - hdf5
  - pytables
  - pip
  - pip:
      - "-r requirements-dev.txt"
